export type JobRow = {
  id: string;
  employer_id: string;
  status: string;
  version: number;
  current_revision: number;
  reason: string | null;
  published_at: string | null;
  employer_name: string;
  employer_type: string;
  employer_verified: boolean;
  revision_id: string;
  title: string;
  category: string;
  region: string;
  salary_cents: number;
  period: string;
  schedule: string;
  hours: string;
  description: string;
  benefits: string;
  number: number;
};
export type EmployerRow = {
  id: string;
  name: string;
  type: string;
  region: string;
  verified: boolean;
  owned: boolean;
};
export type PersonRow = {
  user_id: string;
  region: string;
  category: string;
  availability: string;
  bio: string;
  verified: boolean;
};
export type ApplicationRow = {
  id: string;
  job_id: string;
  worker_id: string;
  revision_id: string;
  status: string;
  version: number;
  created_at: string;
  employer_id: string;
  employer_name: string;
  worker_name: string;
  title: string;
  salary_cents: number;
  period: string;
  schedule: string;
  hours: string;
  region: string;
  revision_number: number;
  category: string;
  bio: string;
  availability: string;
};
export type MessageRow = {
  id: string;
  application_id: string;
  sender_id: string;
  text: string;
  created_at: string;
  sender_name: string;
};
export type ExperienceRow = {
  id: string;
  version: number;
  closure_id: string | null;
  closure_end_date: string | null;
  closure_status: "Pendente" | "Confirmada" | "Recusada" | null;
  closure_worker_confirmed: boolean | null;
  closure_employer_confirmed: boolean | null;
  worker_id: string;
  employer_id: string | null;
  application_id: string | null;
  employer_name: string;
  title: string;
  start_date: string;
  end_date: string | null;
  origin: string;
  worker_confirmed: boolean;
  employer_confirmed: boolean;
  contested: boolean;
  confirmed_at: string | null;
};
export type ReviewRow = {
  id: string;
  experience_id: string;
  author_id?: string;
  employer_id: string;
  employer_name: string;
  rating: number;
  text: string;
  status: string;
  response: string | null;
  moderation_reason: string | null;
  created_at: string;
};
export type CaseRow = {
  id: string;
  author_id: string;
  title: string;
  detail: string;
  status: string;
  resolution: string | null;
  created_at: string;
};
export type AccountRow = {
  id: string;
  name: string;
  suspended: boolean;
  emailVerified: boolean;
  has_person: boolean;
  verified: boolean | null;
};
export type ReportRow = {
  employer_id: string;
  name: string;
  type: string;
  region: string;
  verified: boolean;
  published: number;
  applications: number;
  hires: number;
  confirmed: number;
  reviews: number;
  average: number | null;
};
export type LiveState = {
  user: { id: string; name: string; role: string; roles: string[] } | null;
  person: PersonRow | null;
  employers: EmployerRow[];
  jobs: JobRow[];
  applications: ApplicationRow[];
  messages: MessageRow[];
  experiences: ExperienceRow[];
  reviews: ReviewRow[];
  cases: CaseRow[];
  accounts: AccountRow[];
};
